namespace EraOnline.Shared.Constants;

/// <summary>VB6: OBJTYPE_* constants in Declarations.bas</summary>
public enum ObjectType
{
    UseOnce = 1,
    Weapon = 2,
    Armour = 3,
    MsgBoard = 4,
    PriestNote = 5,
    Food = 6,
    Drink = 7,
    Harp = 8,
    Bagpipe = 9,
    Guitar = 10,
    Drum = 11,
    Necklace = 12,
    Ring = 13,
    Helmet = 14,
    Clothing = 15,
    FishingRod = 16,
    LumberjackAxe = 17,
    Arrow = 18,
    Key = 19,
    Log = 20,
    Campfire = 21,
    Saw = 22,
    Spell = 23,
    Shield = 24,
    CarpentryDrawing = 25,
    BlacksmithingDrawing = 26,
    TailorDrawing = 27,
    SewingKit = 28,
    Cloth = 29,
    FoldedCloth = 30,
    Steel = 31,
    Ore = 32,
    Hammer = 33,
    // 34 unused
    Planks = 35,
    EmptyBowl = 36,
    BowlOfWater = 37,
    RoastedMeat = 38,
    Meat = 39,
    Corpse = 40,
    Gold = 41,
    Furniture = 42,
    HouseDeed = 43,
    Shoes = 44,
    Bandage = 45,
    MerchantBooth = 46,
    Sign = 47,
    Pickaxe = 48
}
